In [ ]:
from codecarbon import EmissionsTracker

tracker = EmissionsTracker()  
tracker.start()
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset, Dataset
import pandas as pd
import torch
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

[codecarbon WARNING @ 17:25:25] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 17:25:25] [setup] RAM Tracking...
[codecarbon INFO @ 17:25:25] [setup] CPU Tracking...
[codecarbon WARNING @ 17:25:27] We saw that you have a Intel(R) Core(TM) i9-14900K but we don't know it. Please contact us.
[codecarbon WARNING @ 17:25:27] No CPU tracking mode found. Falling back on estimation based on TDP for CPU.
 Windows OS detected: Please install Intel Power Gadget to measure CPU

[codecarbon INFO @ 17:25:27] CPU Model on constant consumption mode: Intel(R) Core(TM) i9-14900K
[codecarbon WARNING @ 17:25:27] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 17:25:27] [setup] GPU Tracking...
[codecarbon INFO @ 17:25:27] Tracking Nvidia GPU via pynvml
[codecarbon INFO @ 17:25:27] The below tracking methods have been set up:
                RAM Tracking Method: RAM power estimation model
                CPU Tracking Method: global constant
                GPU Tracking Method: pynvml

[codecarbon INFO @ 17:25:27] >>> Tracker's metadata:
[codecarbon INFO @ 17:25:27]   Platform system: Windows-10-10.0.26100-SP0
[codecarbon INFO @ 17:25:27]   Python version: 3.11.11
[codecarbon INFO @ 17:25:27]   CodeCarbon version: 3.0.4
[codecarbon INFO @ 17:25:27]   Available RAM : 63.781 GB
[codecarbon INFO @ 17:25:27]   CPU count: 32 thread(s) in 32 physical CPU(s)
[codecarbon INFO @ 17:25:27]   CPU model: Intel(R) Core(TM) i9-14900K
[codecarbon INFO @ 17:25:27]   GPU count: 1
[codecarbon INFO @ 17:25:27]   GPU model: 1 x NVIDIA RTX A6000
[codecarbon INFO @ 17:25:27] Emissions data (if any) will be saved to file C:\Users\FA007\Downloads\emissions.csv
C:\Users\FA007\.conda\envs\new2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
device

device(type='cuda')

In [4]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import random
from collections import defaultdict
from genomic_benchmarks.dataset_getters.pytorch_datasets import get_dataset
# Import the genomic benchmark dataset from Hugging Face
from genomic_benchmarks.dataset_getters.pytorch_datasets import DemoMouseEnhancers

# --------------------
# Data Preprocessing
# --------------------




    # Load the genomic benchmark dataset from Hugging Face
train_dset = get_dataset("human_enhancers_ensembl", split="train", version=0)
test_dset  = get_dataset("human_enhancers_ensembl", split="test", version=0)

    # Extract sequences and labels from the datasets
train_seqs = [item[0] for item in train_dset]
train_labels = [item[1] for item in train_dset]
test_seqs = [item[0] for item in test_dset]
test_labels = [item[1] for item in test_dset]
import pandas as pd
# converting the lists to train and test csv
train_df = pd.DataFrame({
    'sequence':train_seqs,
    'target': train_labels
})
test_df = pd.DataFrame({
    'sequence':test_seqs,
    'target': test_labels
})

[codecarbon INFO @ 17:25:42] Energy consumed for RAM : 0.000083 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:25:42] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:25:42] Energy consumed for All CPU : 0.000177 kWh
[codecarbon INFO @ 17:25:42] Energy consumed for all GPUs : 0.001224 kWh. Total GPU Power : 293.4472500452032 W
[codecarbon INFO @ 17:25:42] 0.001485 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:25:57] Energy consumed for RAM : 0.000167 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:25:57] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:25:57] Energy consumed for All CPU : 0.000354 kWh
[codecarbon INFO @ 17:25:57] Energy consumed for all GPUs : 0.002442 kWh. Total GPU Power : 292.07087705052356 W
[codecarbon INFO @ 17:25:57] 0.002963 kWh of electricity used since the beginning.

In [5]:

test_df_new = pd.read_csv(r"D:\genomic benchmark\human_enhancers_ensembl\dnabert-2\ienhancertest.csv")

In [6]:
def kmer_tokenizer(seq, k=6):
    return " ".join([seq[i:i+k] for i in range(len(seq)-k+1)])

train_df["kmer"] = train_df["sequence"].apply(lambda x: kmer_tokenizer(x))
test_df["kmer"] = test_df["sequence"].apply(lambda x: kmer_tokenizer(x))

In [7]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[["kmer", "target"]])
test_dataset = Dataset.from_pandas(test_df[["kmer", "target"]])

In [8]:
from transformers import AutoTokenizer,  AutoModelForMaskedLM
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("LongSafari/hyenadna-large-1m-seqlen-hf", trust_remote_code=True)

# # Load model using EsmModel
# model = AutoModelForMaskedLM.from_pretrained("InstaDeepAI/nucleotide-transformer-v2-100m-multi-species", trust_remote_code=True).to(device)

In [9]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
   "LongSafari/hyenadna-large-1m-seqlen-hf",
    num_labels=2,
    trust_remote_code=True
).to(device)

Some weights of HyenaDNAForSequenceClassification were not initialized from the model checkpoint at LongSafari/hyenadna-large-1m-seqlen-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [10]:
def tokenize_function(examples):
    return tokenizer(
        examples["kmer"],
        padding="max_length",       # pad all sequences to max_length
        truncation=True,
        max_length=512              # ensure fixed 512 tokens
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)


# 6) Now rename "target" → "labels"
train_dataset = train_dataset.rename_column("target", "labels")
test_dataset  = test_dataset.rename_column("target", "labels")
train_dataset.set_format("torch", columns=["input_ids",  "labels"])
test_dataset.set_format("torch", columns=["input_ids",  "labels"])

[codecarbon INFO @ 17:26:12] Energy consumed for RAM : 0.000250 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:26:12] Delta energy consumed for CPU with constant : 0.000178 kWh, power : 42.5 W
[codecarbon INFO @ 17:26:12] Energy consumed for All CPU : 0.000532 kWh
[codecarbon INFO @ 17:26:12] Energy consumed for all GPUs : 0.003667 kWh. Total GPU Power : 292.3251382696722 W
[codecarbon INFO @ 17:26:12] 0.004449 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:26:27] Energy consumed for RAM : 0.000333 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:26:27] Delta energy consumed for CPU with constant : 0.000176 kWh, power : 42.5 W
[codecarbon INFO @ 17:26:27] Energy consumed for All CPU : 0.000708 kWh
[codecarbon INFO @ 17:26:27] Energy consumed for all GPUs : 0.004892 kWh. Total GPU Power : 294.9551251640241 W
[codecarbon INFO @ 17:26:27] 0.005934 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:26:42] Energy consumed for RAM : 0.000416 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:26:42] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:26:42] Energy consumed for All CPU : 0.000886 kWh
[codecarbon INFO @ 17:26:42] Energy consumed for all GPUs : 0.006124 kWh. Total GPU Power : 294.49610532191343 W
[codecarbon INFO @ 17:26:42] 0.007426 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:26:57] Energy consumed for RAM : 0.000499 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:26:57] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:26:57] Energy consumed for All CPU : 0.001062 kWh
[codecarbon INFO @ 17:26:57] Energy consumed for all GPUs : 0.007361 kWh. Total GPU Power : 296.2348070356928 W
[codecarbon INFO @ 17:26:57] 0.008922 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:27:12] Energy consumed for RAM : 0.000581 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:27:12] Delta energy consumed for CPU with constant : 0.000175 kWh, power : 42.5 W
[codecarbon INFO @ 17:27:12] Energy consumed for All CPU : 0.001237 kWh
[codecarbon INFO @ 17:27:12] Energy consumed for all GPUs : 0.008586 kWh. Total GPU Power : 295.6776488655298 W
[codecarbon INFO @ 17:27:12] 0.010405 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:27:27] Energy consumed for RAM : 0.000664 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:27:27] Delta energy consumed for CPU with constant : 0.000176 kWh, power : 42.5 W
[codecarbon INFO @ 17:27:27] Energy consumed for All CPU : 0.001414 kWh
[codecarbon INFO @ 17:27:27] Energy consumed for all GPUs : 0.009830 kWh. Total GPU Power : 298.6610722011668 W
[codecarbon INFO @ 17:27:27] 0.011908 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:27:28] 0.068386 g.CO2eq/s mean an estimation of 2,156.6214133405156 kg.CO2eq/year
[codecarbon INFO @ 17:27:42] Energy consumed for RAM : 0.000747 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:27:42] Delta energy consumed for CPU with constant : 0.000176 kWh, power : 42.5 W
[codecarbon INFO @ 17:27:42] Energy consumed for All CPU : 0.001589 kWh
[codecarbon INFO @ 17:27:42] Energy consumed for all GPUs : 0.011068 kWh. Total GPU Power : 298.3024423401316 W
[codecarbon INFO @ 17:27:43] 0.013404 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:27:57] Energy consumed for RAM : 0.000829 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:27:58] Delta energy consumed for CPU with constant : 0.000176 kWh, power : 42.5 W
[codecarbon INFO @ 17:27:58] Energy consumed for All CPU : 0.001766 kWh
[codecarbon INFO @ 17:27:58] Energy consumed for all GPUs : 0.012325 kWh. Total GPU Power : 300.74136233763545 W
[codecarbon INFO @ 17:27:58] 0.014920 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:28:12] Energy consumed for RAM : 0.000912 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:28:13] Delta energy consumed for CPU with constant : 0.000176 kWh, power : 42.5 W
[codecarbon INFO @ 17:28:13] Energy consumed for All CPU : 0.001941 kWh
[codecarbon INFO @ 17:28:13] Energy consumed for all GPUs : 0.013592 kWh. Total GPU Power : 300.1378586025795 W
[codecarbon INFO @ 17:28:13] 0.016445 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:28:27] Energy consumed for RAM : 0.000992 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:28:28] Delta energy consumed for CPU with constant : 0.000172 kWh, power : 42.5 W
[codecarbon INFO @ 17:28:28] Energy consumed for All CPU : 0.002113 kWh
[codecarbon INFO @ 17:28:28] Energy consumed for all GPUs : 0.014810 kWh. Total GPU Power : 299.6273912789784 W
[codecarbon INFO @ 17:28:28] 0.017916 kWh of electricity used since the beginning.
Map: 100%|██████████| 123872/123872 [02:32<00:00, 810.82 examples/s]
[codecarbon INFO @ 17:28:43] Energy consumed for RAM : 0.001074 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:28:43] Delta energy consumed for CPU with constant : 0.000175 kWh, power : 42.5 W
[codecarbon INFO @ 17:28:43] Energy consumed for All CPU : 0.002288 kWh
[codecarbon INFO @ 17:28:43] Energy consumed for all GPUs : 0.016061 kWh. Total GPU Power : 302.7656949577384 W
[codecarbon INFO @ 17:28:43] 0.019423 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:28:58] Energy consumed for RAM : 0.001157 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:28:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:28:58] Energy consumed for All CPU : 0.002465 kWh
[codecarbon INFO @ 17:28:58] Energy consumed for all GPUs : 0.017307 kWh. Total GPU Power : 298.15378591489457 W
[codecarbon INFO @ 17:28:58] 0.020929 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:29:13] Energy consumed for RAM : 0.001239 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:29:13] Delta energy consumed for CPU with constant : 0.000175 kWh, power : 42.5 W
[codecarbon INFO @ 17:29:13] Energy consumed for All CPU : 0.002640 kWh
[codecarbon INFO @ 17:29:13] Energy consumed for all GPUs : 0.018555 kWh. Total GPU Power : 301.11546883034276 W
[codecarbon INFO @ 17:29:13] 0.022434 kWh of electricity used since the beginning.
Map: 100%|██████████| 30970/30970 [00:38<00:00, 813.83 examples/s]

In [11]:
# 6) Now rename "target" → "labels"

train_dataset.set_format("torch", columns=["input_ids",  "labels"])
test_dataset.set_format("torch", columns=["input_ids",  "labels"])

In [12]:
# train_dataset = train_dataset.rename_column("target", "labels")
# test_dataset  = test_dataset.rename_column("target", "labels")
# train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
# test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

In [13]:
from transformers import TrainingArguments

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
        "f1": f1_score(labels, preds)
    }

# Define training arguments
training_args = TrainingArguments(
    output_dir="D:\genomic benchmark\datasets\dnabert",

    disable_tqdm=False,
    # evaluation_strategy="epoch",
    save_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    # evaluation_strategy="no", 
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    report_to="none",
)

In [14]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
   
    compute_metrics=compute_metrics,
)

In [15]:
import time

# Start timer
start_time = time.time()

# Train the model
trainer.train()

# End timer
end_time = time.time()
elapsed = end_time - start_time

# Report time
print(f"\n🕒 Training took {elapsed:.2f} seconds ({elapsed/60:.2f} minutes)")
# tracker.stop()

[codecarbon INFO @ 17:29:28] Energy consumed for RAM : 0.001321 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:29:28] Delta energy consumed for CPU with constant : 0.000174 kWh, power : 42.5 W
[codecarbon INFO @ 17:29:28] Energy consumed for All CPU : 0.002813 kWh
[codecarbon INFO @ 17:29:28] Energy consumed for all GPUs : 0.019761 kWh. Total GPU Power : 295.18952143564536 W
[codecarbon INFO @ 17:29:28] 0.023896 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:29:28] 0.069003 g.CO2eq/s mean an estimation of 2,176.08725366196 kg.CO2eq/year
[codecarbon INFO @ 17:29:43] Energy consumed for RAM : 0.001404 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:29:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:29:43] Energy consumed for All CPU : 0.002991 kWh
[codecarbon INFO @ 17:29:43] Energy consumed for all GPUs : 0.020981 kWh. Total GPU Power : 292.36251391175705 W
[codecarbon INFO @ 17:29:43] 0.025376 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:29:58] Energy consumed for RAM : 0.001487 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:29:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:29:58] Energy consumed for All CPU : 0.003168 kWh
[codecarbon INFO @ 17:29:58] Energy consumed for all GPUs : 0.022197 kWh. Total GPU Power : 291.7463141061376 W
[codecarbon INFO @ 17:29:58] 0.026853 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:30:13] Energy consumed for RAM : 0.001571 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:30:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:30:13] Energy consumed for All CPU : 0.003345 kWh
[codecarbon INFO @ 17:30:13] Energy consumed for all GPUs : 0.023416 kWh. Total GPU Power : 292.2607685135374 W
[codecarbon INFO @ 17:30:13] 0.028332 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:30:28] Energy consumed for RAM : 0.001654 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:30:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:30:28] Energy consumed for All CPU : 0.003522 kWh
[codecarbon INFO @ 17:30:28] Energy consumed for all GPUs : 0.024642 kWh. Total GPU Power : 294.26521979683963 W
[codecarbon INFO @ 17:30:28] 0.029819 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:30:43] Energy consumed for RAM : 0.001737 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:30:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:30:43] Energy consumed for All CPU : 0.003699 kWh
[codecarbon INFO @ 17:30:43] Energy consumed for all GPUs : 0.025867 kWh. Total GPU Power : 293.49438827172327 W
[codecarbon INFO @ 17:30:43] 0.031303 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:30:58] Energy consumed for RAM : 0.001821 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:30:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:30:58] Energy consumed for All CPU : 0.003876 kWh
[codecarbon INFO @ 17:30:58] Energy consumed for all GPUs : 0.027092 kWh. Total GPU Power : 294.0978230325955 W
[codecarbon INFO @ 17:30:58] 0.032789 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:31:13] Energy consumed for RAM : 0.001904 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:31:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:31:13] Energy consumed for All CPU : 0.004054 kWh
[codecarbon INFO @ 17:31:13] Energy consumed for all GPUs : 0.028318 kWh. Total GPU Power : 294.16158908104603 W
[codecarbon INFO @ 17:31:13] 0.034276 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:31:28] Energy consumed for RAM : 0.001987 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:31:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:31:28] Energy consumed for All CPU : 0.004231 kWh
[codecarbon INFO @ 17:31:28] Energy consumed for all GPUs : 0.029550 kWh. Total GPU Power : 295.60760465210785 W
[codecarbon INFO @ 17:31:28] 0.035768 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:31:28] 0.068355 g.CO2eq/s mean an estimation of 2,155.634773992072 kg.CO2eq/year
[codecarbon INFO @ 17:31:43] Energy consumed for RAM : 0.002071 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:31:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:31:43] Energy consumed for All CPU : 0.004408 kWh
[codecarbon INFO @ 17:31:43] Energy consumed for all GPUs : 0.030778 kWh. Total GPU Power : 294.6858612757163 W
[codecarbon INFO @ 17:31:43] 0.037256 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:31:58] Energy consumed for RAM : 0.002154 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:31:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:31:58] Energy consumed for All CPU : 0.004585 kWh
[codecarbon INFO @ 17:31:58] Energy consumed for all GPUs : 0.032004 kWh. Total GPU Power : 293.96096124741393 W
[codecarbon INFO @ 17:31:58] 0.038742 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:32:13] Energy consumed for RAM : 0.002237 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:32:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:32:13] Energy consumed for All CPU : 0.004762 kWh
[codecarbon INFO @ 17:32:13] Energy consumed for all GPUs : 0.033230 kWh. Total GPU Power : 294.1457706562623 W
[codecarbon INFO @ 17:32:13] 0.040230 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:32:28] Energy consumed for RAM : 0.002321 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:32:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:32:28] Energy consumed for All CPU : 0.004939 kWh
[codecarbon INFO @ 17:32:28] Energy consumed for all GPUs : 0.034457 kWh. Total GPU Power : 294.5366531141492 W
[codecarbon INFO @ 17:32:28] 0.041717 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:32:43] Energy consumed for RAM : 0.002404 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:32:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:32:43] Energy consumed for All CPU : 0.005116 kWh
[codecarbon INFO @ 17:32:43] Energy consumed for all GPUs : 0.035682 kWh. Total GPU Power : 294.01843353430235 W
[codecarbon INFO @ 17:32:43] 0.043203 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:32:58] Energy consumed for RAM : 0.002487 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:32:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:32:58] Energy consumed for All CPU : 0.005293 kWh
[codecarbon INFO @ 17:32:58] Energy consumed for all GPUs : 0.036906 kWh. Total GPU Power : 293.6211581179909 W
[codecarbon INFO @ 17:32:58] 0.044687 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:33:13] Energy consumed for RAM : 0.002571 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:33:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:33:13] Energy consumed for All CPU : 0.005470 kWh
[codecarbon INFO @ 17:33:13] Energy consumed for all GPUs : 0.038131 kWh. Total GPU Power : 293.9710563157239 W
[codecarbon INFO @ 17:33:13] 0.046172 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:33:28] Energy consumed for RAM : 0.002654 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:33:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:33:28] Energy consumed for All CPU : 0.005648 kWh
[codecarbon INFO @ 17:33:28] Energy consumed for all GPUs : 0.039363 kWh. Total GPU Power : 295.54889834576386 W
[codecarbon INFO @ 17:33:28] 0.047664 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:33:28] 0.068514 g.CO2eq/s mean an estimation of 2,160.6508517874286 kg.CO2eq/year
[codecarbon INFO @ 17:33:43] Energy consumed for RAM : 0.002737 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:33:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:33:43] Energy consumed for All CPU : 0.005825 kWh
[codecarbon INFO @ 17:33:43] Energy consumed for all GPUs : 0.040591 kWh. Total GPU Power : 294.6914843736892 W
[codecarbon INFO @ 17:33:43] 0.049153 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:33:58] Energy consumed for RAM : 0.002821 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:33:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:33:58] Energy consumed for All CPU : 0.006002 kWh
[codecarbon INFO @ 17:33:58] Energy consumed for all GPUs : 0.041815 kWh. Total GPU Power : 293.67286894943146 W
[codecarbon INFO @ 17:33:58] 0.050637 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:34:13] Energy consumed for RAM : 0.002904 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:34:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:34:13] Energy consumed for All CPU : 0.006179 kWh
[codecarbon INFO @ 17:34:13] Energy consumed for all GPUs : 0.043038 kWh. Total GPU Power : 293.4418231250936 W
[codecarbon INFO @ 17:34:13] 0.052121 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:34:28] Energy consumed for RAM : 0.002987 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:34:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:34:28] Energy consumed for All CPU : 0.006356 kWh
[codecarbon INFO @ 17:34:28] Energy consumed for all GPUs : 0.044261 kWh. Total GPU Power : 293.36045503732447 W
[codecarbon INFO @ 17:34:28] 0.053605 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:34:43] Energy consumed for RAM : 0.003071 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:34:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:34:43] Energy consumed for All CPU : 0.006533 kWh
[codecarbon INFO @ 17:34:43] Energy consumed for all GPUs : 0.045486 kWh. Total GPU Power : 293.6264672054196 W
[codecarbon INFO @ 17:34:43] 0.055090 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:34:58] Energy consumed for RAM : 0.003154 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:34:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:34:58] Energy consumed for All CPU : 0.006711 kWh
[codecarbon INFO @ 17:34:58] Energy consumed for all GPUs : 0.046707 kWh. Total GPU Power : 292.86317642910706 W
[codecarbon INFO @ 17:34:58] 0.056571 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:35:13] Energy consumed for RAM : 0.003237 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:35:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:35:13] Energy consumed for All CPU : 0.006888 kWh
[codecarbon INFO @ 17:35:13] Energy consumed for all GPUs : 0.047927 kWh. Total GPU Power : 292.7832663338948 W
[codecarbon INFO @ 17:35:13] 0.058052 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:35:28] Energy consumed for RAM : 0.003321 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:35:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:35:28] Energy consumed for All CPU : 0.007065 kWh
[codecarbon INFO @ 17:35:28] Energy consumed for all GPUs : 0.049158 kWh. Total GPU Power : 295.3024803063734 W
[codecarbon INFO @ 17:35:28] 0.059543 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:35:28] 0.068402 g.CO2eq/s mean an estimation of 2,157.114211668628 kg.CO2eq/year
[codecarbon INFO @ 17:35:43] Energy consumed for RAM : 0.003404 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:35:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:35:43] Energy consumed for All CPU : 0.007242 kWh
[codecarbon INFO @ 17:35:43] Energy consumed for all GPUs : 0.050380 kWh. Total GPU Power : 293.23014277447817 W
[codecarbon INFO @ 17:35:43] 0.061025 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:35:58] Energy consumed for RAM : 0.003487 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:35:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:35:58] Energy consumed for All CPU : 0.007419 kWh
[codecarbon INFO @ 17:35:58] Energy consumed for all GPUs : 0.051597 kWh. Total GPU Power : 291.9390388984614 W
[codecarbon INFO @ 17:35:58] 0.062503 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:36:13] Energy consumed for RAM : 0.003571 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:36:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:36:13] Energy consumed for All CPU : 0.007596 kWh
[codecarbon INFO @ 17:36:13] Energy consumed for all GPUs : 0.052819 kWh. Total GPU Power : 293.27481976197504 W
[codecarbon INFO @ 17:36:13] 0.063985 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:36:28] Energy consumed for RAM : 0.003654 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:36:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:36:28] Energy consumed for All CPU : 0.007773 kWh
[codecarbon INFO @ 17:36:28] Energy consumed for all GPUs : 0.054041 kWh. Total GPU Power : 293.28075489301176 W
[codecarbon INFO @ 17:36:28] 0.065468 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:36:43] Energy consumed for RAM : 0.003737 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:36:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:36:43] Energy consumed for All CPU : 0.007950 kWh
[codecarbon INFO @ 17:36:43] Energy consumed for all GPUs : 0.055264 kWh. Total GPU Power : 293.30990583491007 W
[codecarbon INFO @ 17:36:43] 0.066951 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:36:58] Energy consumed for RAM : 0.003821 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:36:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:36:58] Energy consumed for All CPU : 0.008127 kWh
[codecarbon INFO @ 17:36:58] Energy consumed for all GPUs : 0.056484 kWh. Total GPU Power : 292.7079154254238 W
[codecarbon INFO @ 17:36:58] 0.068432 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:37:13] Energy consumed for RAM : 0.003904 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:37:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:37:13] Energy consumed for All CPU : 0.008305 kWh
[codecarbon INFO @ 17:37:13] Energy consumed for all GPUs : 0.057706 kWh. Total GPU Power : 293.27175446237777 W
[codecarbon INFO @ 17:37:13] 0.069915 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:37:28] Energy consumed for RAM : 0.003987 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:37:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:37:28] Energy consumed for All CPU : 0.008482 kWh
[codecarbon INFO @ 17:37:28] Energy consumed for all GPUs : 0.058935 kWh. Total GPU Power : 294.9131999129923 W
[codecarbon INFO @ 17:37:28] 0.071404 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:37:28] 0.068308 g.CO2eq/s mean an estimation of 2,154.150022495268 kg.CO2eq/year
[codecarbon INFO @ 17:37:43] Energy consumed for RAM : 0.004070 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:37:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:37:43] Energy consumed for All CPU : 0.008659 kWh
[codecarbon INFO @ 17:37:43] Energy consumed for all GPUs : 0.060155 kWh. Total GPU Power : 292.58589236845546 W
[codecarbon INFO @ 17:37:43] 0.072884 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:37:58] Energy consumed for RAM : 0.004154 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:37:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:37:58] Energy consumed for All CPU : 0.008836 kWh
[codecarbon INFO @ 17:37:58] Energy consumed for all GPUs : 0.061375 kWh. Total GPU Power : 292.5869114714914 W
[codecarbon INFO @ 17:37:58] 0.074365 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:38:13] Energy consumed for RAM : 0.004237 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:38:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:38:13] Energy consumed for All CPU : 0.009013 kWh
[codecarbon INFO @ 17:38:13] Energy consumed for all GPUs : 0.062596 kWh. Total GPU Power : 292.87404719785104 W
[codecarbon INFO @ 17:38:13] 0.075846 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:38:28] Energy consumed for RAM : 0.004320 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:38:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:38:28] Energy consumed for All CPU : 0.009190 kWh
[codecarbon INFO @ 17:38:28] Energy consumed for all GPUs : 0.063816 kWh. Total GPU Power : 292.82288108091274 W
[codecarbon INFO @ 17:38:28] 0.077327 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:38:43] Energy consumed for RAM : 0.004404 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:38:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:38:43] Energy consumed for All CPU : 0.009367 kWh
[codecarbon INFO @ 17:38:43] Energy consumed for all GPUs : 0.065038 kWh. Total GPU Power : 293.29626137454494 W
[codecarbon INFO @ 17:38:43] 0.078809 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:38:58] Energy consumed for RAM : 0.004487 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:38:58] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:38:58] Energy consumed for All CPU : 0.009545 kWh
[codecarbon INFO @ 17:38:58] Energy consumed for all GPUs : 0.066258 kWh. Total GPU Power : 292.6372498311704 W
[codecarbon INFO @ 17:38:58] 0.080290 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:39:13] Energy consumed for RAM : 0.004570 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:39:13] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:39:13] Energy consumed for All CPU : 0.009722 kWh
[codecarbon INFO @ 17:39:13] Energy consumed for all GPUs : 0.067485 kWh. Total GPU Power : 294.5019313735338 W
[codecarbon INFO @ 17:39:13] 0.081777 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:39:28] Energy consumed for RAM : 0.004654 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:39:28] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:39:28] Energy consumed for All CPU : 0.009899 kWh
[codecarbon INFO @ 17:39:28] Energy consumed for all GPUs : 0.068710 kWh. Total GPU Power : 293.7924237330301 W
[codecarbon INFO @ 17:39:28] 0.083263 kWh of electricity used since the beginning.
[codecarbon INFO @ 17:39:28] 0.068284 g.CO2eq/s mean an estimation of 2,153.417200200802 kg.CO2eq/year
[codecarbon INFO @ 17:39:43] Energy consumed for RAM : 0.004737 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 17:39:43] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 17:39:43] Energy consumed for All CPU : 0.010076 kWh
[codecarbon INFO @ 17:39:43] Energy consumed for all GPUs : 0.069930 kWh. Total GPU Power : 292.60353757479055 W
[codecarbon INFO @ 17:39:43] 0.084743 kWh of electricity used since the beginning.

🕒 Training took 3204.06 seconds (53.40 minutes)

[codecarbon INFO @ 18:22:44] Energy consumed for RAM : 0.019068 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:22:44] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:22:44] Energy consumed for All CPU : 0.040541 kWh
[codecarbon INFO @ 18:22:44] Energy consumed for all GPUs : 0.280177 kWh. Total GPU Power : 294.283901976108 W
[codecarbon INFO @ 18:22:44] 0.339787 kWh of electricity used since the beginning.
[codecarbon INFO @ 18:22:59] Energy consumed for RAM : 0.019152 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:22:59] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:22:59] Energy consumed for All CPU : 0.040718 kWh
[codecarbon INFO @ 18:22:59] Energy consumed for all GPUs : 0.281419 kWh. Total GPU Power : 297.9535139544012 W
[codecarbon INFO @ 18:22:59] 0.341289 kWh of electricity used since the beginning.
[codecarbon INFO @ 18:23:14] Energy consumed for RAM : 0.019235 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:23:14] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:23:14] Energy consumed for All CPU : 0.040895 kWh
[codecarbon INFO @ 18:23:14] Energy consumed for all GPUs : 0.282671 kWh. Total GPU Power : 300.22423085445183 W
[codecarbon INFO @ 18:23:14] 0.342801 kWh of electricity used since the beginning.
[codecarbon INFO @ 18:23:29] Energy consumed for RAM : 0.019318 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:23:29] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:23:29] Energy consumed for All CPU : 0.041072 kWh
[codecarbon INFO @ 18:23:29] Energy consumed for all GPUs : 0.283916 kWh. Total GPU Power : 298.8520969262113 W
[codecarbon INFO @ 18:23:29] 0.344306 kWh of electricity used since the beginning.
[codecarbon INFO @ 18:23:29] 0.068768 g.CO2eq/s mean an estimation of 2,168.657907190791 kg.CO2eq/year
[codecarbon INFO @ 18:23:44] Energy consumed for RAM : 0.019402 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:23:44] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:23:44] Energy consumed for All CPU : 0.041250 kWh
[codecarbon INFO @ 18:23:44] Energy consumed for all GPUs : 0.285161 kWh. Total GPU Power : 298.5634460656658 W
[codecarbon INFO @ 18:23:44] 0.345812 kWh of electricity used since the beginning.
[codecarbon INFO @ 18:23:59] Energy consumed for RAM : 0.019485 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:23:59] Delta energy consumed for CPU with constant : 0.000177 kWh, power : 42.5 W
[codecarbon INFO @ 18:23:59] Energy consumed for All CPU : 0.041427 kWh
[codecarbon INFO @ 18:23:59] Energy consumed for all GPUs : 0.286405 kWh. Total GPU Power : 298.24219293769545 W
[codecarbon INFO @ 18:23:59] 0.347317 kWh of electricity used since the beginning.

In [16]:
tracker.stop()

[codecarbon INFO @ 18:24:06] Energy consumed for RAM : 0.019520 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:24:06] Delta energy consumed for CPU with constant : 0.000074 kWh, power : 42.5 W
[codecarbon INFO @ 18:24:06] Energy consumed for All CPU : 0.041501 kWh
[codecarbon INFO @ 18:24:06] Energy consumed for all GPUs : 0.286926 kWh. Total GPU Power : 299.3317598856501 W
[codecarbon INFO @ 18:24:06] 0.347947 kWh of electricity used since the beginning.

0.24057427648306806

In [18]:
model.save_pretrained("D:\genomic benchmark\datasets\models and tokenizer/hyenadna-ffinetuned_humannontata", safe_serialization=False)

In [19]:
tokenizer.save_pretrained("D:\genomic benchmark\datasets\models and tokenizer/hyenadna-finetuned_humannontata", safe_serialization=False)

('D:\\genomic benchmark\\datasets\\models and tokenizer/hyenadna-finetuned_humannontata\\tokenizer_config.json',
 'D:\\genomic benchmark\\datasets\\models and tokenizer/hyenadna-finetuned_humannontata\\special_tokens_map.json',
 'D:\\genomic benchmark\\datasets\\models and tokenizer/hyenadna-finetuned_humannontata\\added_tokens.json')

In [20]:
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset, Dataset
import pandas as pd
import torch
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

In [22]:
test_df

,sequence,target,kmer
0,GCAATCCTCCAGCCTTGGCCTCCCAAAGTGCTGGGATTACAAGCAT...,0,GCAATC CAATCC AATCCT ATCCTC TCCTCC CCTCCA CTCC...
1,AAACTTTTCCTGCCAAAGTGTCTCCTACTGAAGTCTGTGGCTACTT...,0,AAACTT AACTTT ACTTTT CTTTTC TTTTCC TTTCCT TTCC...
2,ATCATAGGAATATGGTTTCTCTAATGCTATGTATGGCCCCCACCTC...,0,ATCATA TCATAG CATAGG ATAGGA TAGGAA AGGAAT GGAA...
3,CAACCCTTAAGTCCCTACCCTTAAGACCAGTGTAGTACAGATGGTC...,0,CAACCC AACCCT ACCCTT CCCTTA CCTTAA CTTAAG TTAA...
4,AACTGTCAACTCCTGTTTCTGATACTCTGAGGGGGACATGTCTCTC...,0,AACTGT ACTGTC CTGTCA TGTCAA GTCAAC TCAACT CAAC...
...,...,...,...
30965,TGCCACACACACGTGTGGGTGGAAAGAGAGTAAGATACTGAGACTG...,1,TGCCAC GCCACA CCACAC CACACA ACACAC CACACA ACAC...
30966,TGACTGAGGAAAGCCCGAGCTTTTTTTTTTTTTTTTTTGAGACGGA...,1,TGACTG GACTGA ACTGAG CTGAGG TGAGGA GAGGAA AGGA...
30967,GACAGAGTCTTGCTCTGTTGCCCAGGCTGTAGTGCAGTGGTGCCAT...,1,GACAGA ACAGAG CAGAGT AGAGTC GAGTCT AGTCTT GTCT...
30968,GCAAAAAAAAAAAAAAAAAAAAAATTAGAAAACAAAAAAATGCTTA...,1,GCAAAA CAAAAA AAAAAA AAAAAA AAAAAA AAAAAA AAAA...
30969,TCCCCAGAAGTACTCCATTGAAAACAGCTCTGAGAAACATGCCAAG...,1,TCCCCA CCCCAG CCCAGA CCAGAA CAGAAG AGAAGT GAAG...

In [23]:
import pandas as pd
test_df_im = pd.read_csv(r"D:\genomic benchmark\human_tata promoters\non_tata_vs_non_promoter_external_new.csv")

In [24]:
def kmer_tokenizer(seq, k=6):
    return " ".join([seq[i:i+k] for i in range(len(seq)-k+1)])


test_df["kmer"] = test_df["sequence"].apply(lambda x: kmer_tokenizer(x))
test_df_im["kmer"] = test_df_im["sequence"].apply(lambda x: kmer_tokenizer(x))

In [27]:
test_df_new["kmer"] = test_df_new["sequence"].apply(lambda x: kmer_tokenizer(x))

In [25]:
test_dataset = Dataset.from_pandas(test_df[["kmer", "target"]])
test_dataset_im = Dataset.from_pandas(test_df_im[["kmer", "target"]])

In [28]:
test_dataset_new = Dataset.from_pandas(test_df_new[["kmer", "target"]])

In [26]:
def tokenize_function(examples):
    return tokenizer(
        examples["kmer"],
        padding="max_length",       # pad all sequences to max_length
        truncation=True,
        max_length=512              # ensure fixed 512 tokens
    )


test_dataset = test_dataset.map(tokenize_function, batched=True)
test_dataset_im = test_dataset_im.map(tokenize_function, batched=True)

# 6) Now rename "target" → "labels"

test_dataset  = test_dataset.rename_column("target", "labels")
test_dataset_im  = test_dataset_new.rename_column("target", "labels")
test_dataset.set_format("torch", columns=["input_ids", "labels"])
test_dataset_im.set_format("torch", columns=["input_ids",  "labels"])

Map: 100%|██████████| 30970/30970 [00:38<00:00, 814.42 examples/s]
Map: 100%|██████████| 47542/47542 [00:54<00:00, 872.95 examples/s]

In [31]:
test_dataset_new = test_dataset_new.map(tokenize_function, batched=True)

Map: 100%|██████████| 400/400 [00:00<00:00, 1080.65 examples/s]

In [33]:

test_dataset_new.set_format("torch", columns=["input_ids",  "labels"])

In [34]:
from torch.utils.data import DataLoader

test_dataloader = DataLoader(
    test_dataset, batch_size=16, shuffle=False
)

In [36]:
import torch
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

model.eval()
model.to("cuda" if torch.cuda.is_available() else "cpu")

all_preds = []
all_labels = []
i=0
import time

# Start timer
start_time = time.time()
with torch.no_grad():
    for batch in test_dataloader:
        input_ids = batch['input_ids'].to(model.device)
        # attention_mask = batch['attention_mask'].to(model.device)
        labels = batch['labels'].to(model.device)

        outputs = model(input_ids=input_ids)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=-1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        i+=1
        if i%100==0:
            print(str(i)+" done")
end_time = time.time()
elapsed = end_time - start_time

# Report time
print(f"\n🕒 Evaluation took {elapsed:.2f} seconds ({elapsed/60:.2f} minutes)")
# tracker.stop()

100 done
200 done
300 done
400 done
500 done
600 done
700 done
800 done
900 done
1000 done
1100 done
1200 done
1300 done
1400 done
1500 done
1600 done
1700 done
1800 done
1900 done

🕒 Evaluation took 93.49 seconds (1.56 minutes)

In [37]:
tracker.stop()

[codecarbon WARNING @ 18:38:54] Tracker already stopped !
[codecarbon WARNING @ 18:38:54] Background scheduler didn't run for a long period (888s), results might be inaccurate
[codecarbon INFO @ 18:38:54] Energy consumed for RAM : 0.024456 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:38:54] Delta energy consumed for CPU with constant : 0.010490 kWh, power : 42.5 W
[codecarbon INFO @ 18:38:54] Energy consumed for All CPU : 0.051991 kWh
[codecarbon INFO @ 18:38:54] Energy consumed for all GPUs : 0.360563 kWh. Total GPU Power : 298.3371062741914 W
[codecarbon INFO @ 18:38:54] 0.437011 kWh of electricity used since the beginning.

0.3021539317801313

In [38]:
accuracy = accuracy_score(all_labels, all_preds)
precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted')

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

print("\nClassification Report:")
print(classification_report(all_labels, all_preds))

Accuracy:  0.7655
Precision: 0.7656
Recall:    0.7655
F1 Score:  0.7655

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.75      0.76     15485
           1       0.76      0.78      0.77     15485

    accuracy                           0.77     30970
   macro avg       0.77      0.77      0.77     30970
weighted avg       0.77      0.77      0.77     30970

In [39]:
import torch
torch.cuda.empty_cache()

In [40]:
from torch.utils.data import DataLoader

test_dataloader_new = DataLoader(
    test_dataset_new, batch_size=16, shuffle=False
)

In [42]:
import torch
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

model.eval()
model.to("cuda" if torch.cuda.is_available() else "cpu")

all_preds = []
all_labels = []
i=0
import time

# Start timer
start_time = time.time()
with torch.no_grad():
    for batch in test_dataloader_new:
        input_ids = batch['input_ids'].to(model.device)
        # attention_mask = batch['attention_mask'].to(model.device)
        labels = batch['labels'].to(model.device)

        outputs = model(input_ids=input_ids)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=-1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        i+=1
        if i%100==0:
            print(str(i)+" done")
end_time = time.time()
elapsed = end_time - start_time

# Report time
print(f"\n🕒 Evaluation took {elapsed:.2f} seconds ({elapsed/60:.2f} minutes)")
# tracker.stop()

🕒 Evaluation took 1.22 seconds (0.02 minutes)

In [43]:
tracker.stop()

[codecarbon WARNING @ 18:41:15] Tracker already stopped !
[codecarbon WARNING @ 18:41:15] Background scheduler didn't run for a long period (140s), results might be inaccurate
[codecarbon INFO @ 18:41:15] Energy consumed for RAM : 0.025238 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:41:15] Delta energy consumed for CPU with constant : 0.001662 kWh, power : 42.5 W
[codecarbon INFO @ 18:41:15] Energy consumed for All CPU : 0.053653 kWh
[codecarbon INFO @ 18:41:15] Energy consumed for all GPUs : 0.372236 kWh. Total GPU Power : 298.47502394672165 W
[codecarbon INFO @ 18:41:15] 0.451127 kWh of electricity used since the beginning.

0.31191403711515986

In [44]:
accuracy = accuracy_score(all_labels, all_preds)
precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted')

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

print("\nClassification Report:")
print(classification_report(all_labels, all_preds))

Accuracy:  0.5825
Precision: 0.5960
Recall:    0.5825
F1 Score:  0.5673

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.77      0.65       200
           1       0.63      0.40      0.49       200

    accuracy                           0.58       400
   macro avg       0.60      0.58      0.57       400
weighted avg       0.60      0.58      0.57       400

In [45]:
tracker.stop()

[codecarbon WARNING @ 18:42:10] Tracker already stopped !
[codecarbon WARNING @ 18:42:10] Background scheduler didn't run for a long period (55s), results might be inaccurate
[codecarbon INFO @ 18:42:10] Energy consumed for RAM : 0.025544 kWh. RAM Power : 20.0 W
[codecarbon INFO @ 18:42:10] Delta energy consumed for CPU with constant : 0.000650 kWh, power : 42.5 W
[codecarbon INFO @ 18:42:10] Energy consumed for All CPU : 0.054303 kWh
[codecarbon INFO @ 18:42:10] Energy consumed for all GPUs : 0.376804 kWh. Total GPU Power : 298.44537755007724 W
[codecarbon INFO @ 18:42:10] 0.456651 kWh of electricity used since the beginning.

0.3157338251771273